

services:
  postgresql:
    container_name: ms_pg_sql7
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
      - postgres-data2:/data/postgres
    ports:
      - "5435:5432"

    restart: unless-stopped

  pgadmin:
    container_name: ms_pgadmin7
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

    depends_on:
      - postgresql 




volumes:
  postgres-data2:
  pgadmin: