"""Initial reset - Add status field to JobDescription

Revision ID: 4230c4bb44a8
Revises: e330b19087c1
Create Date: 2025-08-06 22:17:01.715805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4230c4bb44a8'
down_revision: Union[str, None] = 'e330b19087c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('status', sa.String(), nullable=False,server_default="open"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'status')
    # ### end Alembic commands ###
