"""Add status field to JobDescription

Revision ID: e330b19087c1
Revises: 
Create Date: 2025-08-06 22:11:42.253384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e330b19087c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ai_feedback_resume_id_fkey', 'ai_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'ai_feedback', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.add_column('job_descriptions', sa.Column('application_limit', sa.Integer(), nullable=False,server_default='20'))
    op.drop_constraint('personal_info_resume_id_fkey', 'personal_info', type_='foreignkey')
    op.create_foreign_key(None, 'personal_info', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_info', type_='foreignkey')
    op.create_foreign_key('personal_info_resume_id_fkey', 'personal_info', 'resumes', ['resume_id'], ['id'])
    op.drop_column('job_descriptions', 'application_limit')
    op.drop_constraint(None, 'ai_feedback', type_='foreignkey')
    op.create_foreign_key('ai_feedback_resume_id_fkey', 'ai_feedback', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###
